/*
Package maxcdn is the golang bindings for MaxCDN's REST API.

This package should be considered beta. The final release will be moved to
`github.com/maxcdn/go-maxcdn`.

Developer Notes:

- Custom types can be (somewhat) easily generated by using `maxcurl` (see: https://github.com/jmervine/go-maxcdn/tree/master/tools/maxcurl) to fetch the raw json output and the `json2struct` tool at http://mervine.net/json2struct to generate a sample struct. In the resulting struct, I recommend changing a `float64` types to `int` types and replacing any resulting `interface{}` types with `string` types.
*/
package maxcdn
